### PR TITLE
Update syntax.php

### PR DESCRIPTION
**Pull request by Juergen-aus-Koeln**
Additional syntax "MULTI" for multi line plugin 
- with separation of the parameters by "|...|" and line breaks in the output by "|+...|"
- Commas are now accepted in normal text because the separation works with "|"

Example:
```
#@CMS_GEFAHR_MULTI~
|Gefahr, Hinweis|
|Überschrift|
|+zweizeilig|
|Hinweistext|
~@#
```

See also issue #3

### CODE REVIEW

**Comment by turnermm** [comment]
How is this supposed to work? What would then be substituted for this?  That is, this is the macro, what would be its replacement?  You can already create multi-line replacements using the HTML format.

**Comment by Juergen-aus-Koeln** [comment]
I think the syntax is a little bit easyer for normal users who have little or no knowledge of html. And the multi-line code input is more clearly arranged. For example with the syntax used up to now the user has to write something like this:
```
#@CMS_GEFAHR_HTML~Gefahr&#44;Hinweis,Überschrift<br>zweizeilig,Hinweistext~@#
```

And with my modification he would be able to write it in a similar way to a table:
```
#@CMS_GEFAHR_MULTI~
|Gefahr, Hinweis|
|Überschrift|
|+zweizeilig|
|Hinweistext|
~@#
```

**Comment by turnermm** [comment]
What is this:
|+zweizeilig|

**Comment by Juergen-aus-Koeln** [comment]
It's a subsequent line for the third passed parameter, analogously to "Überschrift<br>zweizeilig" in the existing "HTML"-syntax.

**Comment by turnermm** [comment]
I think this is a good idea, but I prefer not to add additional syntax, so I've simply reworked it so that the parameters can be placed on separate lines, for instance
```
#@Mountain_Ranges~
Alps, //comment one
Rockies, // comment two
Andes,
Cascades  RANGE
~@#
```
This would also work:
```
#@Mountain_Ranges~

Alps, //comment one

Rockies, // comment two

Andes,
Cascades  RANGE
~@#
```
In either case the result would be:

> In Europe there are the Alps, in North America the Rockies , in South America the Andes. The Cascades RANGE cross B.C. and the U.S. northwest. 

To include a comma, you escape it `Big\, small\, round`

To include a line-break (newline): `Big\nSmall` -- which is what I think you want  with your `+`.

**Comment by Juergen-aus-Koeln** [comment]
First of all, thank you very much for addressing this issue!

I would like to give you a quite complex example from the field (I'm sorry it's German and please forgive me for making it so long):

Here is the definition for "CMS_ACHTUNG_HTML" / "CMS_ACHTUNG_MULTI":
```
<table style="width:100%;" class="exttable">
<tbody><tr>
<td style="width:130px; text-align:center; padding:0px; border-left:none; border-bottom:none; border-top:none;"> 
<img src="/wiki/lib/exe/fetch.php?media=symbole:sicherheit:achtung.png" class="media img-responsive" alt="" width="35">
</td>
<td style="background-color:#E6E6FA; font-size:16pt; text-transform:uppercase; vertical-align:middle; padding:0px 5px;">
<strong>%1</strong>
</td>
</tr>
<tr>
<td rowspan="5" style="border-left:none; border-top:none;">      </td>
<td> <span class="wrap_gross">
<strong>%2 !</strong>
</span> <br>
%3</td>
</tr>
<tr>
<td style="border-bottom:3px inset lightgrey;"> 
<em>%4:</em> <br>
%5</td>
</tr>
</tbody></table>
```
Here is the code with the syntax used up to now:
```
#@CMS_ACHTUNG_HTML~Achtung, Sachschäden durch Brandereignisse, Aufgrund der vorhandenen Brandschutzmaßnahmen schließen wir eine Verletzung von Personen durch Brandereignisse im Maschinenarbeitsraum aus. Ein Brand kann aber wertvolle Maschinenteile zerstören und ggf. übergreifen auf andere Maschinen- und Hallenteile!, Deshalb, • Verwenden Sie für die Ölbearbeitung nur verdampfungsarme Mineralöle mit hohem Flammpunkt.. hoher Viskosität und niedrigem Verdampfungsverlust entsprechend den Anforderungen nach EN 19353.\\ • Pflegen Sie den Kühlschmierstoff und mischen Sie diesen nicht mit anderen Ölen.\\ • Schütten Sie kein Reinigungsmittel in den Kühlschmierstoffbehälter. Schon das Einbringen geringer Mengen an leichtflüchtigen.. brennbaren Flüssigkeiten (Reiniger.. Waschbenzin etc.) kann zu einer erhöhten Brandgefahr führen.\\ • Beachten Sie die Herstelleranweisungen und Sicherheitsdatenblätter des verwendeten Kühlschmierstoffes.\\ • Erzeugen Sie keine Funken oder offenes Feuer.\\ • Verwenden Sie keine brennbaren Betriebsstoffe.\\ • Verwenden Sie keine stumpfen Schneidwerkzeuge.\\ • Säubern Sie ölbenetzte Außenteile.\\ • Halten Sie geeignetes Löschmittel an der Maschine bereithalten. Zum Löschen von Ölbränden eignen sich die Löschmittel Kohlendioxid (CO2) und Argon (Ar).\\ \\ <b>Verhalten Im Notfall!</b>\\ • Ruhe und Besonnenheit bewahren.\\ • Gefahrenbereich sofort verlassen.\\ • Flucht und Rettungswege benutzen.\\ • Hilfe holen: Rufnummer Feuerwehr.. Notruf\\ • Niemals die Maschinentür öffnen.. wenn es brennt (oder unmittelbar danach). Beim Öffnen der Tür kann es aufgrund der schlagartigen Luftzufuhr zu einer heftigen Rückzündung und herausschlagenden Flammen kommen.\\ • Niemals Wiedereinschalten der Maschine unmittelbar nach einem Brand. Heiße Oberflächen sind äußerst wirksame Zündquellen und können beim Einspritzen des KSS sehr heftige Rückzündungen verursachen.\\ • Niemals die Maschine direkt nach einem Brand anfassen. Im Brandfall kann sich das Maschinengehäuse sehr stark erhitzen und heiße Oberflächen bilden. Angeschmorte Elektrokabel und Hydraulikleitungen können zusätzliche Gefahren bilden.~@#
```
And here is my modified syntax:
```
#@CMS_ACHTUNG_MULTI~
|Achtung|
|Sachschäden durch Brandereignisse|
|Aufgrund der vorhandenen Brandschutzmaßnahmen schließen wir eine Verletzung von Personen durch Brandereignisse im Maschinenarbeitsraum aus. Ein Brand kann aber wertvolle Maschinenteile zerstören und ggf. übergreifen auf andere Maschinen- und Hallenteile!|
|Deshalb|
|  • Verwenden Sie für die Ölbearbeitung nur verdampfungsarme Mineralöle mit hohem Flammpunkt, hoher Viskosität und niedrigem Verdampfungsverlust entsprechend den Anforderungen nach EN 19353.|
|+ • Pflegen Sie den Kühlschmierstoff und mischen Sie diesen nicht mit anderen Ölen.|
|+ • Schütten Sie kein Reinigungsmittel in den Kühlschmierstoffbehälter. Schon das Einbringen geringer Mengen an leichtflüchtigen, brennbaren Flüssigkeiten (Reiniger, Waschbenzin etc.) kann zu einer erhöhten Brandgefahr führen.|
|+ • Beachten Sie die Herstelleranweisungen und Sicherheitsdatenblätter des verwendeten Kühlschmierstoffes.|
|+ • Erzeugen Sie keine Funken oder offenes Feuer.|
|+ • Verwenden Sie keine brennbaren Betriebsstoffe.|
|+ • Verwenden Sie keine stumpfen Schneidwerkzeuge.|
|+ • Säubern Sie ölbenetzte Außenteile.|
|+ • Halten Sie geeignetes Löschmittel an der Maschine bereithalten. Zum Löschen von Ölbränden eignen sich die Löschmittel Kohlendioxid (CO2) und Argon (Ar).|
|+ |
|+ <b>Verhalten Im Notfall!</b>|
|+ • Ruhe und Besonnenheit bewahren.|
|+ • Gefahrenbereich sofort verlassen.|
|+ • Flucht und Rettungswege benutzen.|
|+ • Hilfe holen: Rufnummer Feuerwehr, Notruf|
|+ • Niemals die Maschinentür öffnen, wenn es brennt (oder unmittelbar danach). Beim Öffnen der Tür kann es aufgrund der schlagartigen Luftzufuhr zu einer heftigen Rückzündung und herausschlagenden Flammen kommen.|
|+ • Niemals Wiedereinschalten der Maschine unmittelbar nach einem Brand. Heiße Oberflächen sind äußerst wirksame Zündquellen und können beim Einspritzen des KSS sehr heftige Rückzündungen verursachen.|
|+ • Niemals die Maschine direkt nach einem Brand anfassen. Im Brandfall kann sich das Maschinengehäuse sehr stark erhitzen und heiße Oberflächen bilden. Angeschmorte Elektrokabel und Hydraulikleitungen können zusätzliche Gefahren bilden.|
~@#
```
As you can see it's normal, human readable text without any syntax elements inside the text flow (except `"<b>"`) - and especially: using commas. And furthermore, as I have a problem that this text must be translated in several languages, also a translator can understand all context without any queries about the text content due to control characters contained therein.

Finally I would like to send you a screenshot of this example:
Beispiel

**Comment by turnermm** [comment]
I assume this is met by  #21, so am closing.

**Comment by Juergen-aus-Koeln** [comment]
I'm sorry, but that doesn't help me. It´s not good that you can't work with commas within the continuous text.

**Comment by turnermm** [comment]
I'm afraid it is what it is.  If it doesn't meet your needs, use your own version or consult wikimatrix to hire a programmer who might assist you.

**Comment by turnermm** [comment]
You do undeestand, do  you not, that the escape symbol (the backslash) is removed for output to browser?

**Pull request closed without merging**
